deepspeed --master_port=24999 train_ds.py \
--epoch 15 \
--log_base_dir /home/work/data/runs \
--cache_dir /home/work/data \
--json_dir /home/work/data/hangyul/mimic_cxr_final/mimic_cxr_merged_final.json \
--batch_size 128 \
--exp_name lisa_7b_final \
--batch_balance \
--grad_accumulation_steps 1 \
--lora_r 128 \
--lora_alpha 256 \
--resume /home/work/data/runs/lisa_7b_final \